### ISSUE TITLE
Controller details

### ISSUE THREAD

**Issue by enriquea88** [Vatmex/vatmex-core#14]
In controller details pages: https://www.vatmex.com.mx/ops/atc/{CID}/edit 
ability to edit:

-Controller name (in case they have signed in to VATSIM with an all caps, or similarly badly written name)
-Initials
-Status (Active/Inactive)

optional:
-Rank (for some users that show as SUP)

**Comment by gvaldezsan** [comment]
Only Initials will be added, since the rest of the information comes from Vatsim
